# Run `brew bundle` to install all of this.

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'ffmpeg'
brew 'fish'
brew 'go'
brew 'htop-osx'
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'python3'
brew 'sqlite'
brew 'thefuck'
brew 'tor'
brew 'vim'
brew 'youtube-dl'

cask 'calibre'
cask 'docker'
cask 'handbrake'
cask 'irccloud'
cask 'java'
cask 'keybase'
cask 'pgadmin3'
cask 'the-unarchiver'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
